### ISSUE TITLE
Central list of pages

### ISSUE THREAD

**Issue by hugovk** [codeforamerica/office-screen#1]
Idea:

Rather than having all the what-comes-next pages defined in the individual pages, have them in a single location.

This would make it easy to add pages, remove pages, change order, and even allow a random ordering.

This could also define the delays, if it was useful to have different delays for pages with differing visual loads.

Perhaps something like this:
https://stackoverflow.com/questions/3137530/rotating-urls-within-an-iframe

**Comment by migurski** [comment]
Good idea, thanks! Send a PR and I’ll merge?

**Comment by hugovk** [comment]
Coming up!

**Comment by migurski** [comment]
Oops, closing this old issue.

**Comment by hugovk** [comment]
By the way, I was using it and also saw the a problem with Chrome -- after extended use, it'd stay on one page and not load the next.

The problem appears to have been with the onload part. That was there to make sure the next page only loads X minutes after the iframe had finished loading. But with multi-minute waits, this isn't really needed. I removed that part and it's been working well. I left it an unattended Chrome tab for several four-to-five-day stretches without touching the computer and it was still running.

I've just done some merges with the latest upstream, and added configurable timeouts for each page. I'll do more testing and send another PR if all's fine.
